const int MAX_MAIN_POINTS = 80;
const int MAX_BONUS_POINTS = 20;

const int MAX_BEGINNER_POINTS = MAX_MAIN_POINTS - MAX_BONUS_POINTS - 40;
const int MAX_INTERMEDIATE_POINTS = MAX_MAIN_POINTS - MAX_BONUS_POINTS - 20;
const int MAX_ADVANCED_POINTS = MAX_MAIN_POINTS - MAX_BONUS_POINTS;
