// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs7me4_DPLlSK75ej2JfnK9UBTeLYfrkQ',
    appId: '1:365380606260:web:b5621d7168315e728f6d61',
    messagingSenderId: '365380606260',
    projectId: 'dodecathlon12',
    authDomain: 'dodecathlon12.firebaseapp.com',
    storageBucket: 'dodecathlon12.firebasestorage.app',
    measurementId: 'G-84HGJNE7EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpH2cEKFVc7O35CFIIOu6soiuuraxenWI',
    appId: '1:365380606260:android:ed18143a026dac9c8f6d61',
    messagingSenderId: '365380606260',
    projectId: 'dodecathlon12',
    storageBucket: 'dodecathlon12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUYY7SoWSsz3wMJvaSd2u9J-sIeARdhY',
    appId: '1:365380606260:ios:a30bb38cf27a1e2a8f6d61',
    messagingSenderId: '365380606260',
    projectId: 'dodecathlon12',
    storageBucket: 'dodecathlon12.firebasestorage.app',
    iosBundleId: 'com.example.dodecathlon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUYY7SoWSsz3wMJvaSd2u9J-sIeARdhY',
    appId: '1:365380606260:ios:a30bb38cf27a1e2a8f6d61',
    messagingSenderId: '365380606260',
    projectId: 'dodecathlon12',
    storageBucket: 'dodecathlon12.firebasestorage.app',
    iosBundleId: 'com.example.dodecathlon',
  );

}